# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Static frame generated by the corrected pinned TypeScript AGT SDK."""

from __future__ import annotations

import base64
import json

from agentmesh.encryption.channel import ChannelEstablishment, SecureChannel
from agentmesh.encryption.ratchet import EncryptedMessage, MessageHeader
from agentmesh.encryption.x3dh import (
    OneTimePreKey,
    SignedPreKey,
    X25519KeyPair,
    X3DHKeyManager,
)


def _decode(value: str) -> bytes:
    return base64.b64decode(value)


def _responder() -> X3DHKeyManager:
    seed = _decode("IiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiI=")
    public = _decode("oJql9HpnWYAv+VX43C0qFKXJnSO+l/hkEn/5ODRVpPA=")
    return X3DHKeyManager(
        identity_key=X25519KeyPair(
            private_key=_decode("aMPrHNbb3QA31QPmZVIpUAqD9GS+Ysp1O/+ITEN4h3g="),
            public_key=_decode("nY14ucnmZh5VLy8a8CCV7i+HQ/ouYYP0G7cHfvUbU3k="),
        ),
        ed25519_private=seed + public,
        ed25519_public=public,
        signed_pre_key=SignedPreKey(
            key_pair=X25519KeyPair(
                private_key=_decode("xNRKeMYUxhD/igrHtmXDDRrqBd3wUwDS9D9CDWaRuAM="),
                public_key=_decode("qER3v3BtyomITalPR25chse1Px2xAjfmdtbGgGAbVRw="),
            ),
            signature=_decode(
                "kxfk374VaphjAuHFMFfVUlm3etM9QnSVGdrntzqIdqHjDYPnRPaJyZvejw3TOXBmSMNETEYfqqyY2jHL+ZfdBw=="
            ),
            key_id=0,
        ),
        one_time_pre_keys={
            0: OneTimePreKey(
                key_pair=X25519KeyPair(
                    private_key=_decode("zLzf4ohBwjXCH73rcp4eiLx6rYThUFQ9z+ysVTpl47o="),
                    public_key=_decode("mihVajC5/LCFUfaUug2ESMTL6irsp5Cs4vbSBNKwTG8="),
                ),
                key_id=0,
            )
        },
    )


def test_decrypts_typescript_peers_update_fixture() -> None:
    establishment = ChannelEstablishment(
        initiator_identity_key=_decode(
            "ekbhKf2AUEdEhDfkdE8fFXa+jESf31fgxYDTbFz8Zmg="
        ),
        ephemeral_public_key=_decode(
            "9JRLbHOymuW0vUXPuTNPfRpsfIRZAvcgXuvdN0f4C3A="
        ),
        used_one_time_key_id=0,
    )
    channel = SecureChannel.create_receiver(
        _responder(),
        establishment,
        b"did:mesh:ts-parent-fixture|did:mesh:python-child-fixture",
    )
    message = EncryptedMessage(
        header=MessageHeader(
            dh_public_key=_decode(
                "gDzGsIimSNT+TZDz3hNOZwEpBqWjjykG6PBE5tsPGQs="
            ),
            previous_chain_length=0,
            message_number=0,
        ),
        ciphertext=_decode(
            "6w4MrMv6dC3sqYkEkDShhVg/6tZRZl4p6C+Yd4SWo9L8hg8CuLGW70Vd4Y5O4EIV"
            "+NYOdvoZ25dsLDQpoFptSqReD3AkiaeSsnGjW7J0dRJZMkdwwg=="
        ),
    )

    plaintext = channel.receive(message)

    assert json.loads(plaintext) == {
        "type": "peers_update",
        "peers": [{"name": "hermes-child"}],
    }
