import copy
from datetime import datetime, timedelta, timezone
import json
import os
import shlex
import subprocess
import sys
from types import SimpleNamespace
import unittest
from unittest.mock import patch

import observer_cilium_diagnostics as cilium
import observer_network_diagnostics as network
import observer_packet_diagnostics as packets
from observation_diagnostics import CLIENT_FIELDS, CLIENT_TRANSPORT_FIELDS, TARGETS
from test_observer_network_diagnostics import NetworkFixture, TARGET
import test_observer_network_diagnostics as fixtures


# Representative monitor JSON generated by the v1.18.5 verbose structs, not
# Hubble's unrelated flow schema. L4 ports are strings, identities are integers.
# https://github.com/cilium/cilium/blob/v1.18.5/pkg/monitor/datapath_drop.go
# https://github.com/cilium/cilium/blob/v1.18.5/pkg/monitor/datapath_trace.go
# https://github.com/cilium/cilium/blob/v1.18.5/pkg/monitor/dissect_test.go
# LayerString rendering (including tab and bool syntax) is defined here:
# https://github.com/cilium/cilium/blob/v1.18.5/vendor/github.com/gopacket/gopacket/packet.go
DROP = {
    "cpu": "CPU 01:", "type": "drop", "mark": "0x1234", "reason": "Policy denied",
    "source": 123, "bytes": 74, "srcLabel": 12345, "dstLabel": 7, "dstID": 0,
    "Line": 1975, "File": 1, "ExtError": 0, "Ifindex": 8,
    "summary": {
        "ethernet": "Ethernet\t{Contents=[..14..] Payload=[..60..] SrcMAC=00:00:00:00:00:01 DstMAC=00:00:00:00:00:02 EthernetType=IPv4 Length=0}",
        "ipv4": "IPv4\t{Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=1 Flags=DF FragOffset=0 TTL=64 Protocol=TCP Checksum=0 SrcIP=10.244.1.10 DstIP=10.96.0.1 Options=[] Padding=[]}",
        "tcp": "TCP\t{Contents=[..40..] Payload=[] SrcPort=35000 DstPort=443(https) Seq=100 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=64240 Checksum=0 Urgent=0 Options=[TCPOption(MSS:1460)] Padding=[]}",
        "l2": {"src": "00:00:00:00:00:01", "dst": "00:00:00:00:00:02"},
        "l3": {"src": "10.244.1.10", "dst": "10.96.0.1"},
        "l4": {"src": "35000", "dst": "443"},
    },
}
TRACE = {
    "cpu": "CPU 01:", "type": "trace", "mark": "0x1234", "ifindex": "eth0", "state": "new",
    "observationPoint": "to-stack", "traceSummary": "-> stack", "source": 123,
    "bytes": 74, "srcLabel": 12345, "dstLabel": 7, "dstID": 0, "summary": DROP["summary"],
}
# format.go calls PolicyVerdictNotify.DumpInfo even when --json is selected.
# https://github.com/cilium/cilium/blob/v1.18.5/pkg/monitor/format/format.go
# https://github.com/cilium/cilium/blob/v1.18.5/pkg/monitor/datapath_policy.go
VERDICT = ("Policy verdict log: flow 0x1234 local EP ID 123, remote ID 7, proto 6, "
           "egress, action allow, auth: disabled, match L3-L4, "
           "10.244.1.10:35000 -> 172.18.0.3:6443 tcp SYN")
BINDING = {"podUid": "agent-pod-uid", "endpointId": 123, "securityIdentity": 12345,
           "addresses": ["10.244.1.10"]}
DESTINATIONS = {("10.96.0.1", 443), ("172.18.0.3", 6443)}


class PacketProjectionTests(unittest.TestCase):
    def project(self, event):
        raw = event.encode() if isinstance(event, str) else json.dumps(event).encode()
        return packets.project_line(raw, BINDING, DESTINATIONS)

    def test_real_mixed_json_and_policy_text_schema(self):
        drop, trace, verdict = map(self.project, (DROP, TRACE, VERDICT))
        self.assertEqual(drop["verdict"], "drop")
        self.assertEqual(drop["reason"], "policy-denied")
        self.assertEqual(drop["tcpFlags"], ["SYN"])
        self.assertEqual((drop["bpfFile"], drop["bpfLine"], drop["ifindex"]), (1, 1975, 8))
        self.assertEqual(trace["observationPoint"], "to-stack")
        self.assertEqual(trace["verdict"], "trace-not-a-policy-verdict")
        self.assertEqual(verdict["verdict"], "allow")
        self.assertEqual(verdict["apiAddress"], "172.18.0.3")

    def test_policy_audit_and_redirect_are_not_allows(self):
        for action in ("deny", "redirect", "audit"):
            self.assertEqual(self.project(VERDICT.replace("action allow", "action " + action))["verdict"], action)
        self.assertIsNone(self.project(VERDICT.replace("egress", "ingress")))
        self.assertIsNone(self.project({"type": "policy-verdict", "verdict": "allow"}))

    def test_return_path_is_separately_pinned(self):
        event = copy.deepcopy(TRACE)
        event.update(source=0, dstID=123, srcLabel=7, dstLabel=12345, state="reply", observationPoint="to-endpoint")
        event["summary"]["l3"] = {"src": "172.18.0.3", "dst": "10.244.1.10"}
        event["summary"]["l4"] = {"src": "6443", "dst": "35000"}
        event["summary"]["tcp"] = event["summary"]["tcp"].replace("ACK=false", "ACK=true")
        self.assertEqual(self.project(event)["direction"], "ingress")
        self.assertEqual(self.project(event)["tcpFlags"], ["SYN", "ACK"])
        event["dstLabel"] = 54321
        self.assertIsNone(self.project(event))

    def test_unrelated_endpoints_identities_targets_and_ambiguous_direction_rejected(self):
        for key, value in (("source", 124), ("srcLabel", 54321), ("source", True), ("dstID", 2**32)):
            event = copy.deepcopy(DROP)
            event[key] = value
            self.assertIsNone(self.project(event))
        for address, port in (("172.18.0.99", "6443"), ("10.96.0.1", "6443"),
                              ("169.254.169.254", "443"), ("10.96.0.1", 443), ("10.96.0.1", "0")):
            event = copy.deepcopy(DROP)
            event["summary"]["l3"]["dst"] = address
            event["summary"]["l4"]["dst"] = port
            self.assertIsNone(self.project(event))
        self.assertIsNone(self.project(VERDICT.replace("ID 123,", "ID 124,")))

    def test_canaries_are_never_retained(self):
        event = copy.deepcopy(DROP)
        event.update(reason="private-reason-canary", mark="private-mark-canary",
                     cpu="private-cpu-canary", payload="Authorization: Bearer private-token-canary")
        event["summary"]["tcp"] = event["summary"]["tcp"].replace("Payload=[]", "Payload=[private-body-canary]")
        event["summary"]["ipv4"] = "private-ip-string-canary"
        result = self.project(event)
        self.assertEqual(result["reason"], "other-or-unavailable")
        self.assertNotIn("canary", json.dumps(result))
        self.assertNotIn("summary", result)
        self.assertIsNone(self.project(VERDICT + " private-payload-canary"))

    def test_incomplete_duplicate_malformed_and_foreign_schema_are_unobserved(self):
        for raw in (b'{"type":', b"\xff", b'null', b'[]', b'{"type":"drop","type":"trace"}',
                    b'{"flow":{"verdict":"FORWARDED"}}', b"CPU 01: Lost 12 events"):
            self.assertIsNone(packets.project_line(raw, BINDING, DESTINATIONS))
        for edit in (
            lambda value: value.pop("srcLabel"),
            lambda value: value["summary"].pop("tcp"),
            lambda value: value["summary"].update(tunnel={}),
            lambda value: value["summary"].update(udp="private"),
            lambda value: value["summary"].update(tcp="TCP\t{SYN=true}"),
            lambda value: value["summary"].update(tcp=value["summary"]["tcp"] + " SYN=false"),
            lambda value: value.update(summary=[]),
        ):
            event = copy.deepcopy(DROP)
            edit(event)
            self.assertIsNone(self.project(event))


class PacketWindowTests(unittest.TestCase):
    def setUp(self):
        self.api = NetworkFixture()
        self.setup = SimpleNamespace(admin=self.api, cluster={"server": self.api.server})
        with patch.object(network, "selected_origin", return_value=("127.0.0.1", 36443)), \
                patch.object(cilium, "read_projection", side_effect=self.api.read_projection), \
                patch.object(cilium, "read_kube_proxy_projection", side_effect=self.api.read_kube_proxy_projection):
            self.before = cilium.snapshot(self.setup, TARGET)

    def window(self, source):
        command = [sys.executable, "-u", "-c", source]
        with patch.object(packets, "command_for", return_value=(command, BINDING)):
            return packets.Window(self.before)

    def source(self, lines, count=1):
        return (
            "import sys\n"
            "print('native-monitor-started', flush=True)\n"
            f"sys.stdout.buffer.write({lines!r} * {count}); sys.stdout.buffer.flush()\n"
            "sys.stdin.buffer.read()\n"
            "print('\\nnative-monitor-reaped:143', flush=True)\n"
        )

    def test_command_has_only_narrow_read_only_events_and_remote_watchdog(self):
        command, binding = packets.command_for(self.before)
        self.assertEqual(binding["endpointId"], 123)
        self.assertIn("--related-to \"$1\"", command[-3])
        self.assertIn("--json --numeric --type drop --type trace --type policy-verdict", command[-3])
        self.assertIn("95s", command)
        self.assertIn("--kill-after=2s", command)
        for unsafe in ("--hex", "--verbose", "--type l7", "--type capture", "tcpdump", "curl"):
            self.assertNotIn(unsafe, " ".join(command))
        self.assertEqual(command[-1], "123")

    def test_real_pipe_mixed_wire_cleanup_and_idempotence(self):
        lines = json.dumps(DROP).encode() + b"\n" + json.dumps(TRACE).encode() + b"\n"
        window = self.window(self.source(lines))
        try:
            window.thread.join(0.05)
        finally:
            result = window.close()
        self.assertEqual(len(result["events"]), 2)
        self.assertTrue(result["available"])
        self.assertEqual(result["remoteCleanup"], "exact-child-reaped")
        self.assertEqual(result["localCleanup"], "reaped")
        self.assertIsNotNone(window.process.poll())
        self.assertEqual(result["freshRouterRequest"], "unavailable")
        self.assertIs(result, window.close())

    def test_actual_remote_shell_reaps_its_exact_child(self):
        script = packets.MONITOR_SCRIPT
        invocation = next(line for line in script.splitlines() if line.startswith("cilium-dbg "))
        python = shlex.quote(sys.executable)
        source = shlex.quote("import time; time.sleep(60)")
        script = script.replace(invocation, f"{python} -c {source} &")
        with patch.object(packets, "command_for", return_value=(["sh", "-c", script, "test", "123"], BINDING)):
            window = packets.Window(self.before)
        result = window.close()
        self.assertEqual(result["remoteCleanup"], "exact-child-reaped")
        self.assertEqual(result["localCleanup"], "reaped")
        self.assertEqual(result["monitorExitStatus"], 143)

    def test_unobserved_unavailable_and_partial_are_distinct(self):
        for source, category in (
            (self.source(b""), "unobserved"),
            ("import sys; sys.exit(127)", "source-unavailable"),
        ):
            window = self.window(source)
            result = window.close()
            self.assertEqual(result["category"], category)
            self.assertFalse(result["available"])
        window = self.window("print('native-monitor-started', flush=True)\nprint('{\"type\":', end='', flush=True)")
        window.thread.join(1)
        result = window.close()
        self.assertTrue(result["partialLineDiscarded"])
        self.assertFalse(result["available"])

    def test_byte_line_and_event_limits_stop_and_reap(self):
        for lines, count, limit in (
            (b"private-long-line-canary", 1000, "line-limit"),
            (json.dumps(DROP).encode() + b"\n", 110, "event-limit"),
            (b"private-unrelated-canary" * 100 + b"\n", 150, "byte-limit"),
        ):
            original_read, read_sizes = os.read, []
            def counted_read(fd, size):
                data = original_read(fd, size)
                read_sizes.append(len(data))
                return data
            with patch.object(packets.os, "read", side_effect=counted_read):
                window = self.window(self.source(lines, count))
                window.thread.join(2)
                result = window.close()
            self.assertEqual(result["category"], limit)
            self.assertLessEqual(len(result["events"]), packets.MAX_EVENTS)
            self.assertLessEqual(result["bytesRead"], packets.MAX_BYTES + packets.MAX_LINE)
            self.assertEqual(sum(read_sizes), result["bytesRead"])
            self.assertNotIn("canary", json.dumps(result))
            self.assertIsNotNone(window.process.poll())

    def test_wall_clock_bound_stops_idle_source(self):
        # A late record flushed during the cleanup drain must not become evidence.
        source = (
            "import sys\n"
            "print('native-monitor-started', flush=True)\n"
            "sys.stdin.buffer.read()\n"
            f"print({json.dumps(DROP)!r}, flush=True)\n"
            "print('native-monitor-reaped:143', flush=True)\n")
        with patch.object(packets, "MAX_SECONDS", 0.1):
            window = self.window(source)
            window.thread.join(2)
        self.assertFalse(window.thread.is_alive())
        self.assertEqual(window.close()["remoteCleanup"], "exact-child-reaped")
        self.assertEqual(window.close()["events"], [])

    def test_unresponsive_child_is_killed_locally_without_claiming_remote_cleanup(self):
        source = ("import time\n"
                  "print('native-monitor-started', flush=True)\n"
                  "time.sleep(60)\n")
        window = self.window(source)
        result = window.close()
        self.assertFalse(window.thread.is_alive())
        self.assertIsNotNone(window.process.poll())
        self.assertEqual(result["localCleanup"], "reaped")
        self.assertEqual(result["remoteCleanup"], "unverified-remote-timeout-95s-plus-2s")
        self.assertFalse(result["available"])

    def test_stale_provenance_discards_all_positive_packet_evidence(self):
        window = self.window(self.source(json.dumps(DROP).encode() + b"\n"))
        window.thread.join(0.05)
        result = window.finish(self.setup, TARGET, False)
        self.assertFalse(result["available"])
        self.assertEqual(result["events"], [])
        self.assertEqual(result["category"], "provenance-changed")

    def test_failed_launch_has_no_exception_or_process_evidence(self):
        with patch.object(packets.subprocess, "Popen", side_effect=OSError("private-error-canary")):
            window = packets.Window(self.before)
        with patch.object(packets, "request_evidence", return_value={}):
            result = window.finish(self.setup, TARGET, True)
        self.assertFalse(result["available"])
        self.assertNotIn("canary", json.dumps(result))


class PacketRequestTests(unittest.TestCase):
    def setUp(self):
        api = NetworkFixture()
        self.setup = SimpleNamespace(admin=api, cluster={"server": api.server})
        self.before = network.snapshot(self.setup, TARGET)
        self.since = datetime(2026, 9, 14, 10, 0, tzinfo=timezone.utc)
        self.until = self.since + timedelta(seconds=60)
        actor = self.before["actor"]
        self.log = {
            "timestamp": (self.since + timedelta(seconds=30)).isoformat(),
            "target": TARGETS["router"], "private": "private-log-canary",
            "fields": {"message": "Private observation target client pending", "stage": "observer_target_client",
                       "http_status": 0, **{key: True for key in CLIENT_FIELDS + CLIENT_TRANSPORT_FIELDS},
                       "private": "private-body-canary"},
        }
        self.audit = {
            "level": "Metadata", "stage": "ResponseComplete",
            "requestReceivedTimestamp": (self.since + timedelta(seconds=5)).isoformat(),
            "stageTimestamp": (self.since + timedelta(seconds=6)).isoformat(),
            "user": {"username": actor["username"], "uid": actor["serviceAccountUid"],
                     "extra": {"authentication.kubernetes.io/pod-uid": [actor["pods"][0]["uid"]],
                               "authentication.kubernetes.io/pod-name": [actor["pods"][0]["name"]]}},
            "objectRef": {"apiGroup": "kars.azure.com", "apiVersion": "v1alpha1",
                          "resource": "karssandboxes", "namespace": TARGET["workspace"],
                          "name": TARGET["sandbox"], "uid": TARGET["uid"]},
            "verb": "get", "responseStatus": {"code": 403, "message": "private-status-canary"},
            "requestURI": "private-uri-canary", "annotations": {"private": "private-audit-canary"},
        }

    def collect(self, logs=None, audits=None):
        logs = [self.log] if logs is None else logs
        audits = [self.audit] if audits is None else audits
        with patch.object(packets.subprocess, "run", return_value=SimpleNamespace(
                returncode=0, stdout=b"\n".join(json.dumps(value).encode() for value in logs))), \
                patch.object(packets, "read_audit_tail", return_value=b"\n".join(
                    json.dumps(value).encode() for value in audits)):
            return packets.request_evidence(self.setup, TARGET, self.before, self.since, self.until)

    def test_actual_completion_and_fresh_authenticated_request_have_separate_timing(self):
        result = self.collect()
        self.assertEqual(result["routerLogStatus"], "observed")
        self.assertEqual(result["routerCompletions"][0]["completedAfterStartMs"], 30000)
        self.assertEqual(result["freshPodBoundApiRequests"], [{
            "receivedAfterStartMs": 5000, "completedAfterStartMs": 6000, "httpStatus": 403}])
        self.assertEqual(result["packetToRequestCorrelation"], "unavailable")
        self.assertTrue(result["completionDoesNotProveRequestStartedInWindow"])
        self.assertNotIn("canary", json.dumps(result))

    def test_stale_future_and_partial_router_records_never_prove_fresh_request(self):
        for mutation in (
            lambda value: value.pop("timestamp"),
            lambda value: value.update(timestamp=(self.since - timedelta(seconds=1)).isoformat()),
            lambda value: value.update(timestamp=(self.until + timedelta(seconds=1)).isoformat()),
            lambda value: value["fields"].pop("request_built"),
            lambda value: value["fields"].update(tcp_connect_started="true"),
        ):
            value = copy.deepcopy(self.log)
            mutation(value)
            result = self.collect(logs=[value], audits=[])
            self.assertEqual(result["routerLogStatus"], "unobserved")
            self.assertEqual(result["auditStatus"], "unobserved")
            self.assertEqual(result["packetToRequestCorrelation"], "unavailable")

    def test_stale_or_unbound_audit_requests_are_unobserved_not_denied(self):
        for mutation in (
            lambda value: value.update(requestReceivedTimestamp=(self.since - timedelta(seconds=1)).isoformat()),
            lambda value: value.update(stageTimestamp=(self.until + timedelta(seconds=1)).isoformat()),
            lambda value: value.update(stage="RequestReceived"),
            lambda value: value["user"].update(uid="replacement"),
            lambda value: value["user"]["extra"].update({"authentication.kubernetes.io/pod-uid": ["foreign"]}),
            lambda value: value["objectRef"].update(uid="replacement"),
            lambda value: value["objectRef"].update(name="foreign"),
            lambda value: value.update(impersonatedUser={"username": "foreign"}),
        ):
            value = copy.deepcopy(self.audit)
            mutation(value)
            result = self.collect(logs=[], audits=[value])
            self.assertEqual(result["auditStatus"], "unobserved")
            self.assertEqual(result["freshPodBoundApiRequests"], [])

    def test_request_bounds_and_unavailable_sources(self):
        result = self.collect(logs=[self.log] * 100, audits=[self.audit] * 100)
        self.assertLessEqual(len(result["routerCompletions"]), 12)
        self.assertLessEqual(len(result["freshPodBoundApiRequests"]), 12)
        self.until = self.since + timedelta(seconds=111)
        result = self.collect()
        self.assertEqual(result["routerLogStatus"], "unavailable")
        self.assertEqual(result["auditStatus"], "unavailable")
        with patch.object(packets.subprocess, "run", side_effect=OSError("private-canary")), \
                patch.object(packets, "read_audit_tail", side_effect=OSError("private-canary")):
            result = packets.request_evidence(self.setup, TARGET, self.before, self.since,
                                              self.since + timedelta(seconds=60))
        self.assertEqual(result["routerLogStatus"], "unavailable")
        self.assertEqual(result["auditStatus"], "unavailable")
        self.assertNotIn("canary", json.dumps(result))


class PacketIntegrationTests(unittest.TestCase):
    def test_existing_policy_experiment_survives_missing_monitor_and_keeps_failure(self):
        fixture = fixtures.ObserverNetworkTests()
        fixture.setUp()
        result = fixture.collect()
        self.assertEqual(result["originalResult"], "failed")
        self.assertFalse(result["cniAcceptanceQualified"])
        self.assertTrue(result["policyCreated"])
        self.assertEqual(result["cleanup"], "uid-rv-deletion-verified")
        self.assertFalse(result["baselinePackets"]["available"])
        self.assertFalse(result["policyWindowPackets"]["available"])

    def test_monitors_bracket_existing_policy_and_cleanup_even_after_stability_failure(self):
        for mutation in (False, True):
            fixture = fixtures.ObserverNetworkTests()
            fixture.setUp()
            order = []
            windows = []
            def start(_before):
                label = len(windows)
                order.append(("start", label))
                window = SimpleNamespace(
                    finish=lambda *_args: packets.empty_result(),
                    close=lambda: order.append(("close", label)) or packets.empty_result())
                windows.append(window)
                return window
            def created():
                order.append(("create", None))
                if mutation:
                    fixture.api.policy_revisions = [15, 15]
                    fixture.api.objects[fixtures.POD]["status"]["containerStatuses"][0]["restartCount"] = 1
            fixture.api.after_create = created
            with patch.dict(os.environ, fixtures.ENV), \
                    patch.object(network, "command", side_effect=lambda *args, **_kwargs:
                        json.dumps(fixtures.redacted_context()) if args[0] == "kubectl" else "bridge-native"), \
                    patch.object(cilium, "read_projection", side_effect=fixture.api.read_projection), \
                    patch.object(cilium, "read_kube_proxy_projection", side_effect=fixture.api.read_kube_proxy_projection), \
                    patch.object(network, "api_outcomes", return_value=fixtures.OUTCOMES), \
                    patch.object(network.time, "sleep"), patch.object(packets, "start", side_effect=start):
                result = network.collect(fixture.setup, TARGET, copy.deepcopy(fixtures.FAILED))
            self.assertEqual(order[:3], [("start", 0), ("start", 1), ("create", None)])
            self.assertIn(("close", 0), order)
            self.assertIn(("close", 1), order)
            self.assertEqual(result["cleanup"], "uid-rv-deletion-verified")
            self.assertEqual(result["originalResult"], "failed")
            if mutation:
                self.assertFalse(result["policyWindowPackets"]["provenanceUnchanged"])


if __name__ == "__main__":
    unittest.main()
