// kars Bridge — structured AGT tool-policy builder. Instead of hand-writing the
// agentmesh PolicyEngine YAML (the "embarrassing" part), the operator toggles
// capability presets and adds optional custom allow/deny rules; this module
// generates a valid ToolPolicy spec (appliesTo + agtProfile.inline YAML).
//
// The AGT DSL: `policies:` is a priority-ordered list of rules; each rule has a
// type (capability), an allow (`allowed_actions`) or deny (`denied_actions`)
// list of glob action patterns, and a priority (higher = evaluated first, first
// match wins). Action format examples: shell:<cmd>, inference:*, tool:<name>,
// foundry:<tool>:*, spawn:create:*, mesh:send:*.

export interface PolicyPreset {
  id: string;
  label: string;
  description: string;
  effect: "allow" | "deny";
  actions: string[];
  priority: number;
  /** On by default in a new policy (safe, common baseline). */
  defaultOn: boolean;
}

export const POLICY_PRESETS: PolicyPreset[] = [
  {
    id: "deny-dangerous-shell",
    label: "Block dangerous shell",
    description: "Deny destructive/networking shell commands (rm, mkfs, dd, nmap, nc, shutdown…).",
    effect: "deny",
    priority: 100,
    defaultOn: true,
    actions: [
      "shell:rm", "shell:mkfs", "shell:shutdown", "shell:reboot", "shell:dd",
      "shell:nmap", "shell:nc", "shell:netcat", "shell:socat", "shell:nsenter",
      "shell:unshare", "shell:chroot",
    ],
  },
  {
    id: "safe-shell",
    label: "Safe shell commands",
    description: "Allow common read/dev shell tools (ls, cat, grep, git, python, node, npm, curl, jq…).",
    effect: "allow",
    priority: 90,
    defaultOn: true,
    actions: [
      "shell:ls", "shell:cat", "shell:grep", "shell:find", "shell:echo", "shell:head",
      "shell:tail", "shell:wc", "shell:sort", "shell:uniq", "shell:diff", "shell:python",
      "shell:python3", "shell:pip", "shell:node", "shell:npm", "shell:git", "shell:curl",
      "shell:jq", "shell:sed", "shell:awk",
    ],
  },
  {
    id: "inference",
    label: "Inference & image generation",
    description: "Allow the agent to call models and image generation.",
    effect: "allow",
    priority: 80,
    defaultOn: true,
    actions: ["inference:*", "image_generation:*"],
  },
  {
    id: "foundry-tools",
    label: "Foundry tools",
    description: "Allow Azure AI Foundry tools: web search, code execute, file search, memory, evaluations…",
    effect: "allow",
    priority: 80,
    defaultOn: true,
    actions: [
      "foundry:web_search:*", "foundry:code_execute:*", "foundry:file_search:*",
      "foundry:memory:*", "foundry:image_generation:*", "foundry:conversations:*",
      "foundry:evaluations:*", "foundry:agents:*",
    ],
  },
  {
    id: "mcp-tools",
    label: "MCP / connected-service tools",
    description: "Allow tool calls to connected MCP servers (scoped further by each server's allow-list).",
    effect: "allow",
    priority: 70,
    defaultOn: true,
    actions: ["tool:*"],
  },
  {
    id: "spawn",
    label: "Spawn sub-agents",
    description: "Allow the agent to spawn governed sub-agents (each attenuated below the parent).",
    effect: "allow",
    priority: 70,
    defaultOn: false,
    actions: ["spawn:create:*"],
  },
  {
    id: "mesh",
    label: "Mesh messaging",
    description: "Allow encrypted inter-agent messages over the mesh (send + receive).",
    effect: "allow",
    priority: 70,
    defaultOn: false,
    actions: ["mesh:send:*", "mesh:receive"],
  },
];

export interface CustomRule {
  id: number;
  name: string;
  effect: "allow" | "deny";
  actions: string; // comma/space separated
  priority: number;
}

function yamlList(actions: string[]): string {
  return actions.map((a) => `      - "${a}"`).join("\n");
}

/** Generate the agentmesh PolicyEngine YAML from selected presets + custom rules. */
export function generateAgtProfile(
  agent: string,
  presetIds: Set<string>,
  custom: CustomRule[],
): string {
  const rules: string[] = [];
  for (const p of POLICY_PRESETS) {
    if (!presetIds.has(p.id)) continue;
    const key = p.effect === "deny" ? "denied_actions" : "allowed_actions";
    rules.push(
      `  - name: ${p.id}\n    type: capability\n    ${key}:\n${yamlList(p.actions)}\n    priority: ${p.priority}`,
    );
  }
  for (const c of custom) {
    const actions = c.actions.split(/[\s,]+/).map((s) => s.trim()).filter(Boolean);
    if (!c.name.trim() || actions.length === 0) continue;
    const key = c.effect === "deny" ? "denied_actions" : "allowed_actions";
    const safeName = c.name.trim().toLowerCase().replace(/[^a-z0-9-]+/g, "-");
    rules.push(
      `  - name: ${safeName}\n    type: capability\n    ${key}:\n${yamlList(actions)}\n    priority: ${c.priority}`,
    );
  }
  return [
    "# Generated by the kars Bridge policy builder — agentmesh PolicyEngine format.",
    "# Rules are evaluated by priority (higher first); first match wins.",
    'version: "1.0"',
    `agent: ${agent || "custom-policy"}`,
    "policies:",
    rules.join("\n"),
    "",
  ].join("\n");
}

/** Build the full ToolPolicy spec object from the builder inputs. */
export function buildToolPolicySpec(opts: {
  agent: string;
  sandboxLabelKey: string;
  sandboxLabelValue: string;
  toolGlob: string;
  presetIds: Set<string>;
  custom: CustomRule[];
  approvalMode: "none" | "always" | "aboveThreshold";
  approvalThreshold: string;
}): Record<string, unknown> {
  const appliesTo: Record<string, unknown> = {};
  if (opts.sandboxLabelKey.trim()) {
    appliesTo.sandboxMatchLabels = { [opts.sandboxLabelKey.trim()]: opts.sandboxLabelValue.trim() || "true" };
  }
  if (opts.toolGlob.trim() && opts.toolGlob.trim() !== "*") {
    appliesTo.tool = opts.toolGlob.trim();
  }
  const spec: Record<string, unknown> = {
    appliesTo,
    agtProfile: { inline: generateAgtProfile(opts.agent, opts.presetIds, opts.custom) },
  };
  if (opts.approvalMode !== "none") {
    const approval: Record<string, unknown> = { mode: opts.approvalMode };
    if (opts.approvalMode === "aboveThreshold" && opts.approvalThreshold.trim()) {
      approval.threshold = opts.approvalThreshold.trim();
    }
    spec.approval = approval;
  }
  return spec;
}
